// Simulated content of the DOT file
const dotContent = `
  digraph PRODUCT {
    __SystemOverview [shape=box, label="This graph represents a FizzBuzz processing system for an educational video.\\nActors produce numbers divisible by 3 and 5.\\nA processor combines them into FizzBuzz messages.\\nA console printer outputs summary statistics every 10 seconds.\\nAn ErrorLogger captures any processing errors."];

    DivBy3Producer [label="Produces numbers divisible by 3\\nmod::div_by_3_producer\\nAtLeastEvery(1ms)"];
    DivBy5Producer [label="Produces numbers divisible by 5\\nmod::div_by_5_producer\\nAtLeastEvery(1ms)"];
    FizzBuzzProcessor [label="Generates Fizz, Buzz, and FizzBuzz records\\nmod::fizz_buzz_processor\\nOnEvent(numbers:1)"];
    ConsolePrinter [label="Prints summary counts to console\\nmod::console_printer\\nOnEvent(print_signal:1)"];
    TimerActor [label="Triggers printing every 10 seconds\\nmod::timer_actor\\nAtLeastEvery(10sec)"];
    ErrorLogger [label="Logs processing errors\\nmod::error_logger\\nOnEvent(errors:1)"];

    DivBy3Producer -> FizzBuzzProcessor [label="name::numbers <NumberMessage> >>TakeCopy #1000"];
    DivBy5Producer -> FizzBuzzProcessor [label="name::numbers <NumberMessage> >>TakeCopy #1000"];
    FizzBuzzProcessor -> ConsolePrinter [label="name::fizzbuzz_messages <FizzBuzzMessage> >>Take #10000"];
    TimerActor -> ConsolePrinter [label="name::print_signal <PrintSignal> >>Take #1"];
    FizzBuzzProcessor -> ErrorLogger [label="name::errors <ErrorMessage> >>Take #100"];

    __NumberMessage [shape=box, label="NumberMessage is a union type for numbers from DivBy3Producer and DivBy5Producer.\\nVariants: DivBy3Number, DivBy5Number."];
    __NumberMessage -> DivBy3Producer [style=dotted];
    __NumberMessage -> DivBy5Producer [style=dotted];
    __NumberMessage -> FizzBuzzProcessor [style=dotted];

    __FizzBuzzMessage [shape=box, label="FizzBuzzMessage contains 'Fizz', 'Buzz', or 'FizzBuzz' records.\\nGenerated by FizzBuzzProcessor for ConsolePrinter."];
    __FizzBuzzMessage -> FizzBuzzProcessor [style=dotted];
    __FizzBuzzMessage -> ConsolePrinter [style=dotted];

    __ErrorMessage [shape=box, label="ErrorMessage captures any errors during processing.\\nUsed by FizzBuzzProcessor to send to ErrorLogger."];
    __ErrorMessage -> FizzBuzzProcessor [style=dotted];
    __ErrorMessage -> ErrorLogger [style=dotted];
  }
`;

// Ensure the DOM is fully loaded before running the script
document.addEventListener('DOMContentLoaded', function () {
  // Parse the DOT content
  const graph = graphlibDot.parse(dotContent);

  // Convert the graph to nodes and links
  const nodes = graph.nodes().map(nodeId => ({
    id: nodeId,
    label: graph.node(nodeId).label || nodeId,
  }));

  const links = graph.edges().map(edge => ({
    source: edge.v,
    target: edge.w,
    label: edge.label || '',
  }));

  // Render the graph in 3D
  const Graph = ForceGraph3D()(document.getElementById('3d-graph'))
    .graphData({ nodes, links })
    .nodeLabel('label')
    .linkLabel('label')
    .nodeAutoColorBy('id')
    .linkDirectionalArrowLength(3.5)
    .linkDirectionalArrowRelPos(1)
    .linkCurvature(0.25);
});